#### Question 1 ####
countNA <- function(vec){
    # Counts the number of missing elements from a vector
    #
    # Args:
    #   vec: a vector of values to be checekd for missing elements
    #
    # Return:
    #   The number of missing elements
    return(sum(is.na(vec)))
}
test.Q1 <- c("Bob", NA, "Jim", NA, "Test", NA, "NA", "I wonder how it handled that last one", NA)
countNA(test.Q1) # 4, so "NA" didn't fool R


#### Question 2 ####
dfMissing <- function(df){
    # Counts the number of missing element in a data frame
    #
    # Args:
    #   df: a data frame that will be checked for missing elements
    #
    # Returns:
    #   A named vector with the number of missing elements in each column the
    #   names corresponds to the names of dataframe columns
    # Error Check
    if(is.data.frame(df) == FALSE){
        return("The object is not a data frame.")
    }
    missing <- apply(df, 2, function(x) countNA(x))
    return(missing)
}

vec1.Q2 <- c("Jill", "Dave", NA, "Ciera", NA, "Tom")
vec2.Q2 <- c(25, NA, 54, 28, NA, 12)
vec3.Q2 <- c("Engineer", "Night of Ni", NA, "President", "HR", "Guru")
info.Q2 <- data.frame(Name = vec1.Q2, Age = vec2.Q2, Occupation = vec3.Q2)
dfMissing(info.Q2) # Name 2  Age 2  Occupation 1


#### Question 3 ####
numMedian <- function(vec){
    # Returns the median of a vector
    # Helper function for numSum()
    # Args:
    #   vec: a numeric vector to be evaluated
    #
    # Return:
    #   The location of the median and the value of the median.
    #   The second location is used for even length lists and
    #   computation of Q3
    # Error Check
    if(is.numeric(vec) == FALSE){
        return("The input vector is not numeric.")
    }
    vec.sort <- sort(vec)
    vec.length <- length(na.omit(vec.sort))
    if(vec.length %% 2 == 0){
        median <- (vec.sort[vec.length / 2] + vec.sort[vec.length / 2 + 1]) / 2
        location1 <- vec.length / 2
        location2 <- vec.length / 2 + 1
    } else {
        median <- vec.sort[vec.length %/% 2 + 1 ]
        location1 <- vec.length %/% 2 + 1
        location2 <- vec.length %/% 2 + 1
    }
    return(c(location1, location2, median))
}

numSum <- function(vec){
    # Generates the min, max, mean, median, 1st quartile, 3rd quartile,
    # standard deviation, and the number of missing values.
    #
    # Args:
    #   vec: a numeric vector to be analyzed 
    #
    # Returns:
    #   A named vector conatining the numeric values generated by the
    #   analysis.
    # Error Check
    if(is.numeric(vec) == FALSE){
        return("The input vector is not numeric.")
    }
    vec.sort <- sort(vec)
    vec.mean <- sum(na.omit(vec))/length(na.omit(vec))
    vec.min <- vec.sort[1]
    vec.max <- vec.sort[length(na.omit(vec.sort))]
    vec.median <- numMedian(vec)
    quart.1 <- numMedian(vec.sort[1:vec.median[1]])
    quart.3 <- numMedian(vec.sort[vec.median[2]:length(na.omit(vec.sort))])
    standard.deviation <- sqrt(sum((na.omit(vec.sort) - vec.mean)^2) / (length(na.omit(vec.sort))-1))
    vec.missing <- countNA(vec)
    result <- list(Mean = vec.mean, Minimum = vec.min, Q1 = quart.1[3], Median = vec.median[3], Q3 = quart.3[3], Maximum = vec.max, SD = standard.deviation, Missing = vec.missing)
    return(result)
}

test.Q3 <- c(NA, 42, 12, 3, NA, 6, NA, -4, NA, 42, 5, 32, -1, NA, 7)


#### Question 4 ####
charSum <- function(c.vec){
    # Takes a character or facotr vector and computes the following: number of
    # distinct elements, the most commonly occuring element, the number of
    # times this element occurs, and the number of missing values.
    #
    # Args:
    #   c.vec: Character vector
    #
    # Returns:
    #   A named list with the results of the analysis. If there is a tie
    #   the first element of the tie is returned.
    # Error Check
    if(is.character(c.vec) == FALSE & is.factor(c.vec) == FALSE){
        return("The vector is not a character or factor vector.")
    }
    summary <- table(c.vec)
    distinct <- length(summary)
    most <- names(which.max(summary))
    occur <- summary[[most]]
    missing <- countNA(c.vec)
    result <- list(Distinct = distinct, Mode = most, Occurs = occur, Missing = missing)
    return(result)
}

test.Q4 <- c("Bob", "Ni", "test", NA, "Bob", NA, "test", "Ni", "Huh", NA, "watch", "Elderbery", NA, "shrubbery", NA)
charSum(test.Q4)

test.Q4a <- as.factor(test.Q4)
charSum(test.Q4a)


#### Question 5 ####
logicalSum <- function(l.vec){
    # Takes a logical vector and returns the number of true values the number
    # of false values, the proportion of true values and the number of
    # missing values.
    #
    # Args:
    #   l.vec: Logical vector
    #
    # Returns:
    #   A named list containg the results of the analysis.
    # Error Check
    if(is.logical(l.vec) == FALSE){
        return("The vector is not a logical vector")
    }
    num.true <- sum(na.omit(l.vec))
    num.false <- length(na.omit(l.vec)) - num.true
    true.prop <- num.true / length(na.omit(l.vec))
    missing <- countNA(l.vec)
    result <- list(True = num.true, False = num.false, TrueProportion = true.prop, Missing = missing)
    return(result)
}

test.Q5 <- c(T, F, F, NA, T, T, NA, F, T, NA, T, F, T, F, T)
logicalSum(test.Q5)

#### Question 6 ####
dfSum <- function(df){
    # Takes a data frame and breaks the columns up by type to be summarized.
    #
    # Args:
    #   df: a data frame to be analyzed
    #
    # Returns:
    #   A named list of lists containing the results.
    # Error Check
    if(is.data.frame(df) == FALSE){
        return("The object is not a data frame.")
    }
    names <- colnames(df)
    sum.result <- list()
    for(i in 1:ncol(df)){
        column <- df[,i]
        if(is.numeric(column) == TRUE){
            result <- numSum(column)
        } else if(is.character(column) == TRUE | is.factor(column) == TRUE){
            result <- charSum(column)
        } else {
            result <- logicalSum(column)
        }
        sum.result <- append(sum.result, list(result))
    }
    names(sum.result) = names
    return(sum.result)
}

test.df <- data.frame(Numeric = test.Q3, Character = test.Q4, Factor = test.Q4a, Logical = test.Q5)
summary <- dfSum(test.df)
str(summary)
